spring:
  rabbitmq:
    host: 111.33.127.10
    username: sit_hcsp
    password: Tisi123456
    virtual-host: sit_hcsp
    port: 5672
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  mvc:
    servlet:
      load-on-startup: 1
mqtt:
  clientId: rabbitmq-client
  username: admin
  password: public
  host: tcp://127.0.0.1:1883
#  host: tcp://10.200.49.101:1884
  will-topic: rabbitmq-client-will
  will-qos: 0
server:
  port: 8001
upload:
    picture:
      path: C:/Users/Administrator.Win10-2022YZGQX/Desktop/picture
      upload-url: http://127.0.0.1:8001/resource/file/upload
    video:
      path: C:/Users/Administrator.Win10-2022YZGQX/Desktop/video
      save-path: C:/Users/Administrator.Win10-2022YZGQX/Desktop/save-video
      upload-url: http://127.0.0.1:8001/resource/file/upload

